version: "3.5"

networks:
  default:
    external:
      name: bridge

volumes:
  freenas:
    driver_opts:
      type: "nfs"
      o: "addr=cosmos.cloudgeni.us,nolock,soft,rw"
      device: ":/mnt/tank/plexbox"

services:
  forked-daapd:
    build: .
    restart: always
    network_mode: "host"
    volumes:
      - "/var/cache/forked-daapd:/var/cache/forked-daapd"
      - "./forked-daapd.conf.erb:/etc/forked-daapd.conf.erb"
      - type: volume
        source: freenas
        target: /media
        volume:
          nocopy: true
    environment:
      DAAPD_NAME: Dockerized
